import { useEffect, useState } from "react";
import { Link, useLocation, useNavigate, useSearchParams } from "react-router-dom";
import { FaArrowLeft, FaStar, FaRegStar, FaCheckCircle } from "react-icons/fa";
import { createReview, updateReview } from "../../services/reviewService";
import { getHostelById } from "../../services/hostelService";
import { getApiErrorMessage } from "../../utils/apiError";

export default function ReviewCreate() {
  const navigate=useNavigate(); const location=useLocation(); const [params]=useSearchParams();
  const hostelId=params.get("hostelId")||location.state?.review?.hostelId?._id||location.state?.review?.hostelId||"";
  const editing=location.state?.review||null;
  const [hostel,setHostel]=useState(null); const [rating,setRating]=useState(Number(editing?.rating||5)); const [hover,setHover]=useState(0); const [comment,setComment]=useState(editing?.comment||""); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{if(hostelId)getHostelById(hostelId).then(r=>setHostel(r.data?.hostel||r.data?.data||r.data)).catch(()=>{})},[hostelId]);
  const submit=async(e)=>{e.preventDefault();if(!hostelId){setError("Hostel information is missing.");return}if(!comment.trim()){setError("Please write a review.");return}try{setLoading(true);setError("");const payload={rating,comment:comment.trim()};if(editing)await updateReview(editing._id,payload);else await createReview({hostelId,...payload});navigate("/student/reviews")}catch(err){setError(getApiErrorMessage(err))}finally{setLoading(false)}};
  return <main className="min-h-screen bg-slate-50 px-4 py-6 dark:bg-slate-950 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl"><Link to="/student/reviews" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-indigo-600 dark:text-slate-400"><FaArrowLeft className="text-xs"/> Back to reviews</Link><section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="bg-gradient-to-r from-indigo-600 via-violet-600 to-fuchsia-600 p-6 text-white sm:p-8"><p className="text-xs font-bold uppercase tracking-widest text-indigo-100">Student Feedback</p><h1 className="mt-2 text-2xl font-extrabold sm:text-3xl">{editing?"Edit your review":"Share your experience"}</h1><p className="mt-2 text-sm text-indigo-100">{hostel?.propertyTitle||"Your hostel"}</p></div><form onSubmit={submit} className="space-y-6 p-6 sm:p-8">{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-medium text-red-700 dark:border-red-900/50 dark:bg-red-950/30 dark:text-red-400">{error}</div>}<div><label className="mb-3 block text-sm font-bold text-slate-700 dark:text-slate-300">Your Rating</label><div className="flex items-center gap-2">{[1,2,3,4,5].map(i=><button type="button" key={i} onMouseEnter={()=>setHover(i)} onMouseLeave={()=>setHover(0)} onClick={()=>setRating(i)} className="text-3xl transition hover:scale-110">{i<=(hover||rating)?<FaStar className="text-amber-400"/>:<FaRegStar className="text-slate-300 dark:text-slate-600"/>}</button>)}<span className="ml-2 text-sm font-bold text-slate-500">{rating}/5</span></div></div><div><div className="mb-2 flex justify-between"><label className="text-sm font-bold text-slate-700 dark:text-slate-300">Your Review</label><span className="text-xs text-slate-400">{comment.length}/1000</span></div><textarea required rows={7} maxLength={1000} value={comment} onChange={e=>setComment(e.target.value)} placeholder="What did you like? What should other students know?" className="w-full resize-none rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm leading-6 outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20 dark:border-slate-700 dark:bg-slate-800 dark:text-white"/></div><div className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><Link to="/student/reviews" className="rounded-xl border border-slate-200 px-5 py-3 text-center text-sm font-bold text-slate-600 dark:border-slate-700 dark:text-slate-300">Cancel</Link><button disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-indigo-600 to-violet-600 px-6 py-3 text-sm font-bold text-white shadow-lg disabled:opacity-60">{loading?"Saving...":<><FaCheckCircle/> {editing?"Update Review":"Submit Review"}</>}</button></div></form></section></div></main>;
}
