import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { FaStar, FaPlus, FaEdit, FaTrash, FaPen } from "react-icons/fa";
import { updateReview, deleteReview } from "../../services/reviewService";
import api from "../../api/axios";
import { getApiErrorMessage } from "../../utils/apiError";

export default function Reviews() {
  const [reviews,setReviews]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const load=async()=>{try{setLoading(true);setError("");const r=await api.get("/user/reviews");setReviews(r.data?.data||r.data?.reviews||r.data||[])}catch(e){setError(getApiErrorMessage(e))}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const remove=async(id)=>{if(!window.confirm("Delete this review?"))return;try{await deleteReview(id);setReviews(x=>x.filter(r=>r._id!==id))}catch(e){setError(getApiErrorMessage(e))}};
  return <main className="min-h-screen bg-slate-50 px-4 py-6 dark:bg-slate-950 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl">
    <section className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 text-xs font-bold uppercase tracking-widest text-indigo-600 dark:text-indigo-400">Student Feedback</p><h1 className="text-3xl font-extrabold text-slate-900 dark:text-white">My Reviews</h1><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">Manage the ratings and experiences you have shared with the StudNest community.</p></div><Link to="/student/reviews/create" className="inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-indigo-600 via-violet-600 to-fuchsia-600 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-indigo-500/20"><FaPlus/> Write Review</Link></section>
    {error&&<div className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-medium text-red-700 dark:border-red-900/50 dark:bg-red-950/30 dark:text-red-400">{error}</div>}
    {loading?<div className="grid gap-5 md:grid-cols-2">{[1,2].map(i=><div key={i} className="h-48 animate-pulse rounded-2xl bg-white dark:bg-slate-900"/>)}</div>:reviews.length===0?<div className="rounded-3xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center dark:border-slate-700 dark:bg-slate-900"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-amber-50 text-2xl text-amber-500 dark:bg-amber-900/20"><FaStar/></div><h2 className="mt-5 text-xl font-bold text-slate-900 dark:text-white">No reviews yet</h2><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">After an eligible stay, share your experience to help other students.</p><Link to="/student/bookings" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white">View bookings</Link></div>:<div className="grid gap-5 md:grid-cols-2">{reviews.map(r=>{const hostel=r.hostelId||r.hostel||{};return <article key={r._id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg dark:border-slate-800 dark:bg-slate-900 sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-indigo-600 dark:text-indigo-400">Your review</p><h2 className="mt-1 text-lg font-bold text-slate-900 dark:text-white">{hostel.propertyTitle||hostel.name||"Hostel"}</h2></div><div className="flex items-center gap-1 rounded-full bg-amber-50 px-3 py-1.5 text-sm font-bold text-amber-600 dark:bg-amber-900/20 dark:text-amber-400"><FaStar/>{Number(r.rating||0)}/5</div></div><div className="mt-4 flex gap-1">{[1,2,3,4,5].map(i=><FaStar key={i} className={i<=Number(r.rating||0)?"text-amber-400":"text-slate-200 dark:text-slate-700"}/>)}</div><p className="mt-4 rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-600 dark:bg-slate-800 dark:text-slate-300">{r.comment||"No comment provided."}</p><div className="mt-4 flex items-center justify-between gap-3"><span className="text-xs text-slate-400">{r.createdAt?new Date(r.createdAt).toLocaleDateString("en-IN"):""}</span><div className="flex gap-2"><Link to={`/student/reviews/create?hostelId=${hostel._id||r.hostelId}`} state={{review:r}} className="inline-flex items-center gap-2 rounded-lg border border-indigo-200 px-3 py-2 text-xs font-bold text-indigo-600 hover:bg-indigo-50 dark:border-indigo-900/50 dark:text-indigo-400"><FaEdit/> Edit</Link><button onClick={()=>remove(r._id)} className="inline-flex items-center gap-2 rounded-lg bg-red-50 px-3 py-2 text-xs font-bold text-red-600 hover:bg-red-100 dark:bg-red-950/20 dark:text-red-400"><FaTrash/> Delete</button></div></div></article>})}</div>}
  </div></main>;
}
